development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: awesomr_development
  pool: 5
  username: root
  password:
  hostname: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: awesomr_test
  pool: 5
  username: root
  password:
  hostname: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: awesomr
  pool: 5
  username: root
  password:
  hostname: localhost